language: python
sudo: false
cache: pip
python:
  - "3.6.2"
services:
  - postgresql
before_script:
  - psql -c "CREATE USER condobus WITH PASSWORD 'condobus' CREATEDB" -U postgres
  - psql -c "CREATE EXTENSION postgis" -U postgres
  - psql -c "CREATE DATABASE test_condobus" -U postgres
script:
  - make setup
  - make test
  - make lint
  - make isort
