language: python
sudo: false
cache: pip
python:
  - "3.6.2"
services:
  - postgresql

# The following is necessary because of https://github.com/travis-ci/travis-ci/issues/6972
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

before_script:
  - psql -c "CREATE USER condobus WITH PASSWORD 'condobus' SUPERUSER" -U postgres
script:
  - make setup
  - make test
  - make lint
  - make isort
