language: python
sudo: false
cache: pip

python:
  - "3.6.2"

services:
  - postgresql

# The following is necessary because of https://github.com/travis-ci/travis-ci/issues/6972
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

before_script:
  - psql -c "CREATE USER condobus WITH PASSWORD 'condobus' SUPERUSER" -U postgres
  - nvm install 8.5
  - nvm use 8.5

script:
  - make setup
  - make test
  - make lint-backend
  - make isort
