version: "3.3"

services:

  db:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: condobus
      POSTGRES_PASSWORD: condobus
      POSTGRES_DB: condobus
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - "5050:5050"

  backend:
    restart: always
    build: ./backend
    command: "./docker/web-start.sh"
    environment:
      DB_HOST: db
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    restart: always
    build: ./frontend
    command: "yarn start"
    volumes:
      - ./frontend/src:/code/src
      - ./frontend/public:/code/public
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pg_data:
