version: "3.3"

services:

  db:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: condobus
      POSTGRES_PASSWORD: condobus
      POSTGRES_DB: condobus
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql/data

  web:
    restart: always
    build: .
    command: "./docker/web-start.sh"
    environment:
      DB_HOST: db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db


