# Generated by Django 2.0b1 on 2017-10-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Rules')),
            ],
            options={
                'verbose_name': 'Organization',
            },
        ),
    ]
