# Generated by Django 2.0.1 on 2018-01-18 01:54

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_auto_20171030_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='org.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='org.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='org.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-22.99977, -43.36063), srid=4326, verbose_name='Location')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_points', to='transport.Route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'StopPoint',
                'verbose_name_plural': 'StopPoints',
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Version')),
                ('validity', models.DateField(verbose_name='Validity')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sheets', to='transport.Direction', verbose_name='Direction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sheets', to='org.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'TimeSheet',
                'verbose_name_plural': 'TimeSheets',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=200, null=True, verbose_name='Departure')),
                ('destination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination')),
                ('time', models.TimeField(verbose_name='Time')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='transport.Bus', verbose_name='Bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='transport.Route', verbose_name='Route')),
                ('time_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='transport.TimeSheet', verbose_name='TimeSheet')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
            },
        ),
    ]
