# Generated by Django 2.0b1 on 2018-01-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_direction_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(blank=True, max_length=200, null=True, verbose_name='Departure')),
                ('destination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination')),
                ('time', models.TimeField(verbose_name='Time')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='transport.Bus', verbose_name='Bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='transport.Route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
            },
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='name',
        ),
        migrations.AddField(
            model_name='travel',
            name='time_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='transport.TimeSheet', verbose_name='TimeSheet'),
        ),
    ]
