# Generated by Django 2.0.1 on 2018-01-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20180103_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['name'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
    ]
